//
// Created by LE, Duc Anh on 6/10/15.
//

#ifndef CLOUD_E_CPLUS_FOUNDATION_COMMON_ICOMPOUNDASSIGNABLE_H
#define CLOUD_E_CPLUS_FOUNDATION_COMMON_ICOMPOUNDASSIGNABLE_H

#endif //CLOUD_E_CPLUS_FOUNDATION_ICOMPOUNDASSIGNABLE_H
